# Generated by Django 5.1.4 on 2026-03-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_fcm_token"),
    ]

    operations = []
